# yaml-language-server: $schema=https://raw.githubusercontent.com/docker/cli/master/cli/compose/schema/data/config_schema_v3.9.json
version: '3.9'

services:
  project-curve-client:
    build: ./
    container_name: project-curve-redirect
    ports:
      - '6011:5000'
    restart: unless-stopped
